Created search and filters components for articles
NotJediYet/SportsHub.UI pull request #35
Opened 2022-09-13 10:42 UTC by Juli11V

Create a filters components.
Create a search components.
Create an articles components.
Create service for filterArticles.

2022-09-16 08:45 UTC, markoparfeniuk requested changes

2022-09-16 08:45 UTC, markoparfeniuk commented on src/components/AdminContextAreaManagement/AdminContentArea/AdminFiltersContentArea/AdminFiltersContentArea.js
> +
177-181 extra blank lines

2022-09-16 08:45 UTC, markoparfeniuk commented on src/components/AdminContextAreaManagement/AdminContentArea/AdminFiltersContentArea/AdminFiltersContentArea.js
> +
Could you please remove the blanks in lines 15-52?

2022-09-16 08:45 UTC, markoparfeniuk commented on src/components/AdminContextAreaManagement/AdminContentArea/AdminContentArea.js
> +
Here is an empty line

2022-09-16 08:45 UTC, markoparfeniuk commented on src/components/AdminContextAreaManagement/AdminContentArea/AdminSearchContentArea/AdminSearchContentArea.js
> +
Here is another blank line :)

2022-09-16 08:45 UTC, markoparfeniuk commented on src/components/AdminContextAreaManagement/AdminContentArea/AdminSearchContentArea/AdminSearchContentArea.js
> +
And here is too

2022-09-16 08:45 UTC, markoparfeniuk commented on src/services/TeamService/TeamService.js
And the last one :)

2022-09-19 09:06 UTC, markoparfeniuk approved these changes

2022-09-19 18:18 UTC, NotJediYet approved these changes

2022-09-22 09:03 UTC, NotJediYet approved these changes

2022-09-28 17:43 UTC, closed without merging