Allow admin users to add a new team and to edit existing one on the portal
NotJediYet/SportsHub.UI pull request #38
Opened 2022-09-25 16:56 UTC by Yurii-Hubych

### Summary of changes:

- Add the ability to create a new team;
- Add the ability to edit existing team;

[User Story Requirements SPHUB-78](https://github.com/dark-side/lanthanum/tree/master/sports_hub_portal/web_application_features/maintain_navigation/user_stories/add_new_team)

[User Story Requirements SPHUB-79](https://github.com/dark-side/lanthanum/tree/master/sports_hub_portal/web_application_features/maintain_navigation/user_stories/edit_existing_team)

2022-09-25 18:16 UTC, foxerest requested changes

2022-09-25 18:16 UTC, foxerest commented on src/components/AdminTeams/AdminTeamsComponents/DropDown/DropDown.js
> +
extra black line here, could pls remove this one?

2022-09-25 18:16 UTC, foxerest commented on src/components/ProfileManagement/ProfileNavigation/ProfileNavigation.js
> +
delete extra blank line pls

2022-09-25 19:39 UTC, foxerest approved these changes

2022-09-25 22:04 UTC, nadiiakhasyshyn approved these changes
LGBT!

2022-09-26 11:32 UTC, NotJediYet approved these changes

2022-09-26 11:32 UTC, NotJediYet commented
LGTM!

2022-09-26 12:07 UTC, merged